version: 2.1

filter-semantic-tag: &filter-semantic-tag
    tags:
        only: /^v?\d+\.\d+\.\d+$/
    branches:
        ignore: /.*/

remote_worker: &remote_worker
    setup_remote_docker:
        version: edge
        docker_layer_caching: true

orbs:
    vro: kohirens/version-release@4.0.2

executors:
    image-builder:
        docker: # see https://circleci.com/docs/building-docker-images/#docker-version
            - image: cimg/base:current
              auth:
                  username: ${DH_USER}
                  password: ${DH_PASS}
        resource_class: small
        environment:
            DOCKER_BUILDKIT: 1

    go-get-latest:
        docker: # see https://github.com/kohirens/go-get-latest
            - image: kohirens/go-get-latest:0.6.0
              auth:
                  username: ${DH_USER}
                  password: ${DH_PASS}
        resource_class: small

parameters:
    app_name:
        default: "go-release"
        type: string
    ctx_auto_release:
        default: kohirens-automation
        description: CircleCI context containing automation secrets.
        type: string
    ctx_docker:
        default: kohirens-automation-dockerhub
        description: CircleCI context containing Docker Hub secrets.
        type: string
    dh_img_repo:
        default: kohirens/go-release
        description: Docker image repository
        type: string
    ssh_finger:
        default: "SHA256:aKLk+IhiY6p1yhzVueC/7Pjyu9sU3SM2VVPHHb3GMJU"
        description: SSH fingerprint.
        type: string
    triggered_flow:
        default: "workflow-selector"
        description: Indicates with workflow should run.
        type: string
    variables_file:
        default: variables.env
        type: string

jobs:
    co:
        executor: go-get-latest
        steps:
            - add_ssh_keys:
                fingerprints:
                    - << pipeline.parameters.ssh_finger >>
            - checkout
            - run:
                  name: "Get Alpine & Go latest versions"
                  command: |
                      ALPINE_VER=$(go-get-latest alpine2)
                      GO_VER=$(go-get-latest go)
                      GO_VER_NO_PATCH=$(go-get-latest --no-patch go)
                      echo "ALPINE_VER=${ALPINE_VER}" > << pipeline.parameters.variables_file >>
                      echo "GO_VER=${GO_VER}" >> << pipeline.parameters.variables_file >>
                      echo "GO_VER_NO_PATCH=${GO_VER_NO_PATCH}" >> << pipeline.parameters.variables_file >>
                      echo "DH_IMG=<<pipeline.parameters.dh_img_repo>>:${GO_VER_NO_PATCH}" >> <<pipeline.parameters.variables_file>>
                      cat <<pipeline.parameters.variables_file>>
            - persist_to_workspace:
                root: .
                paths: [ . ]

    run-test:
        docker:
            - image: cimg/go:1.22
        steps:
            - attach_workspace: { at: "." }
            - restore_cache:
                keys:
                    - go-mod-v1-{{ checksum "go.mod" }}
            - run:
                name: Install Dependencies
                command: go mod tidy
            - save_cache:
                key: go-mod-v1-{{ checksum "go.mod" }}
                paths:
                    - "/home/circleci/go/pkg/mod"
                    - "/go/pkg/mod"
            - run:
                  name: Run tests
                  command: |
                      go test ./...
            - persist_to_workspace:
                root: .
                paths: [ ./* ]

    run-img-test:
        executor: image-builder
        steps:
            - attach_workspace: { at: "." }
            - *remote_worker
            - run:
                  name: Build image and run test
                  command: |
                      docker build --rm \
                          -f .docker/go-release/Dockerfile \
                          -t go-release:alpha \
                          --target "release" .
                      docker run --rm --entrypoint go go-release:alpha version
                      docker run --rm go-release:alpha -version
                      docker rmi go-release:alpha

    publish-execs:
        parameters:
            app_name:
                type: string
            build_tag:
                default: << pipeline.git.tag >>
                type: string
        docker:
            - image: kohirens/circleci-go:0.4.1
              auth:
                  username: ${DH_USER}
                  password: ${DH_PASS}
        steps:
            - attach_workspace: { at: "." }
            - run:
                name: Build go-release
                command: |
                    go generate
                    go build
            - run:
                name: Build and publish executables
                command: |
                    echo "Publishing GitHub release '<< parameters.build_tag >>' assets"
                    src_dir=.
                    go generate "${src_dir}"
                    ./go-release build \
                        "${src_dir}" \
                        "<< parameters.app_name >>" \
                        "<< parameters.build_tag >>" \
                        "kohirens" \
                        "go-release" \
                        "${GH_TOKEN}"

    publish-image:
        executor: image-builder
        parameters:
            docker_file:
                type: string
        steps:
            - attach_workspace: { at: "." }
            - *remote_worker
            - run:
                name: Build and push image
                command: |
                    export $(< <<pipeline.parameters.variables_file>>)
                    echo "${DH_PASS}" | docker login -u "${DH_USER}" --password-stdin
                    echo ""
                    echo "Building ${DH_IMG}"
                    docker build --rm \
                        -f "<< parameters.docker_file >>" \
                        -t "${DH_IMG}" \
                        --build-arg ALPINE_VER --build-arg GO_VER \
                        --target "release" .
                    echo ""
                    echo "Pushing ${DH_IMG}"
                    docker push "${DH_IMG}"
                    echo ""
                    echo "Cleaning up ${DH_IMG}"
                    docker rmi "${DH_IMG}"

workflows:
    quality-control:
        jobs:
            - co:
                  filters: { branches: { ignore: [main, auto-update-changelog] } }
            - run-test:
                  context: << pipeline.parameters.ctx_docker >>
                  requires: [ co ]
            - run-img-test:
                  context: << pipeline.parameters.ctx_docker >>
                  requires: [ co ]

    workflow-selector:
        when:
            and:
                - equal: [main, << pipeline.git.branch >>]
                - equal: ["workflow-selector", << pipeline.parameters.triggered_flow >>]
        jobs:
            - vro/workflow-selector:
                context: << pipeline.parameters.ctx_auto_release >>
                ssh_finger: << pipeline.parameters.ssh_finger >>

    publish-changelog:
        when:
            and:
                - equal: ["publish-changelog", << pipeline.parameters.triggered_flow >>]
        jobs:
            - vro/publish-changelog:
                context: << pipeline.parameters.ctx_auto_release >>
                ssh_finger: << pipeline.parameters.ssh_finger >>

    publish-release-tag:
        when:
            and:
                - equal: ["publish-release-tag", << pipeline.parameters.triggered_flow >>]
        jobs:
            - co:
                  context: << pipeline.parameters.ctx_docker >>
            - vro/tag-and-release:
                  context: << pipeline.parameters.ctx_auto_release >>
                  requires: [ co ]
                  do_attach_workspace: true
                  do_checkout: false
                  tag_env_var: "GO_VER"

    on-tag-release:
        jobs:
            - co:
                context: << pipeline.parameters.ctx_docker >>
                filters:
                    <<: *filter-semantic-tag
            - run-test:
                  context: << pipeline.parameters.ctx_docker >>
                  requires: [ co ]
            - publish-execs:
                context: << pipeline.parameters.ctx_auto_release >>
                filters:
                    <<: *filter-semantic-tag
                app_name: << pipeline.parameters.app_name >>
                requires: [ run-test ]
            - publish-image:
                name: publish-release-image
                context: << pipeline.parameters.ctx_docker >>
                filters:
                    <<: *filter-semantic-tag
                requires: [ run-test ]
                docker_file: ".docker/go-release/Dockerfile"


    scheduled-weekly-check:
        when:
            and:
                - equal: ["scheduled-weekly-check", << pipeline.parameters.triggered_flow >>]
                - equal: [ main, << pipeline.git.branch >> ]
        jobs:
            - co:
                  context:
                      - << pipeline.parameters.ctx_auto_release >>
                      - << pipeline.parameters.ctx_docker >>
            - publish-image:
                  context:
                      - << pipeline.parameters.ctx_auto_release >>
                      - << pipeline.parameters.ctx_docker >>
                  filters:
                      <<: *filter-semantic-tag
                  requires: [ co  ]
                  docker_file: ".docker/go-release/Dockerfile"
